# Generated by Django 4.0.4 on 2022-05-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labName', models.CharField(max_length=120)),
                ('labBuilding', models.CharField(max_length=120)),
                ('labStatus', models.CharField(choices=[('working', 'operating'), ('not working', 'borken')], default='working', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcStatus', models.CharField(choices=[('working', 'operating'), ('not working', 'borken')], default='working', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('jobTitle', models.CharField(max_length=80)),
                ('userName', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
