# Generated by Django 4.0.4 on 2022-05-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_labs_pcs_users_delete_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='labChairsCount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labs',
            name='labFNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labs',
            name='labPcsCount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcs',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcs',
            name='labId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
