# Generated by Django 4.0.4 on 2022-05-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_labs_labchairscount_labs_labfnumber_labs_labpcscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
